language: android
jdk: oraclejdk8

android:
  components:
    - extra-android-m2repository
    - extra-google-m2repository
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - build-tools-22.0.1
    - android-22
  licenses:
    - android-sdk-license-.+

script:
    - cp SensitiveDataTemplate.txt app/src/main/java/com/criptext/monkeychatandroid/SensitiveData.java 
    - ./gradlew clean test
